"""Add insurance_company to Policy

Revision ID: 049ca9522340
Revises: e675ea6d79d4
Create Date: 2024-09-22 02:01:22.256192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '049ca9522340'
down_revision: Union[str, None] = 'e675ea6d79d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
